import {useRef,useState,useLayoutEffect,cloneElement} from 'react';
import {LineChart,Line,AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ReferenceLine,ComposedChart,ErrorBar,PieChart,Pie,Cell} from 'recharts';
import {REGIME_COLORS} from '../lib/api';
// Mount chart content only after it has a measurable box, including hidden mobile columns.
const ResponsiveContainer=({children})=>{
 const ref=useRef(null);const [size,setSize]=useState(null);
 useLayoutEffect(()=>{const node=ref.current;if(!node)return;const measure=()=>{const {width,height}=node.getBoundingClientRect();setSize(width>0&&height>0?{width:Math.floor(width),height:Math.floor(height)}:null);};measure();const observer=new ResizeObserver(measure);observer.observe(node);return()=>observer.disconnect();},[]);
 return <div ref={ref} style={{width:'100%',height:'100%',minWidth:0}}>{size?cloneElement(children,size):null}</div>;
};
const colors=['#4dd5c4','#7592b4','#a987e3','#e9b665'];
export const Chart=({data,keys,x,type='line',height=240,domain,reference,id='chart',percent=false})=><div data-testid={id} className="chart-wrap" style={{height,minWidth:0}}><ResponsiveContainer width="100%" height="100%">{type==='area'?<AreaChart data={data} margin={{top:10,right:12,bottom:4,left:-20}}><CartesianGrid stroke="var(--border-soft)" vertical={false}/><XAxis dataKey={x} tick={{fill:'var(--text-muted)',fontSize:10}} minTickGap={22}/><YAxis domain={domain} tick={{fill:'var(--text-muted)',fontSize:10}}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)',borderRadius:5}}/>{keys.map((key,i)=><Area key={key} dataKey={key} stackId="a" fill={REGIME_COLORS[key]||colors[i]} stroke={REGIME_COLORS[key]||colors[i]} fillOpacity={.68} isAnimationActive={false}/>)}</AreaChart>:type==='bar'?<BarChart data={data} margin={{top:10,right:12,bottom:4,left:-20}}><CartesianGrid stroke="var(--border-soft)" vertical={false}/><XAxis dataKey={x} tick={{fill:'var(--text-muted)',fontSize:10}}/><YAxis domain={domain} tick={{fill:'var(--text-muted)',fontSize:10}}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/><Legend wrapperStyle={{fontSize:10}}/>{keys.map((key,i)=><Bar key={key} dataKey={key} fill={colors[i%4]} radius={[2,2,0,0]} isAnimationActive={false}/>)}</BarChart>:<LineChart data={data} margin={{top:10,right:12,bottom:4,left:-20}}><CartesianGrid stroke="var(--border-soft)" vertical={false}/><XAxis dataKey={x} tick={{fill:'var(--text-muted)',fontSize:10}} minTickGap={20}/><YAxis domain={domain} tick={{fill:'var(--text-muted)',fontSize:10}} tickFormatter={v=>percent?`${v}%`:v}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/><Legend wrapperStyle={{fontSize:10}}/>{reference!=null&&<ReferenceLine y={reference} stroke="#7d899a" strokeDasharray="4 4"/>}{keys.map((key,i)=><Line key={key} type="monotone" dataKey={key} stroke={REGIME_COLORS[key]||colors[i%4]} strokeWidth={2} dot={false} strokeDasharray={key==='Useful skill'?'5 5':undefined} isAnimationActive={false}/>)}</LineChart>}</ResponsiveContainer></div>;
export const Sparkline=({data,id})=><div className="sparkline" data-testid={id}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><Area dataKey="probability" stroke="#58c8b4" fill="#58c8b4" fillOpacity={.09} strokeWidth={1.5} isAnimationActive={false}/><YAxis hide domain={[0,100]}/></AreaChart></ResponsiveContainer></div>;
export const Donut=({mix})=><div className="donut" data-testid="regime-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={Object.entries(mix).map(([name,value])=>({name,value}))} dataKey="value" innerRadius="58%" outerRadius="80%" paddingAngle={2} isAnimationActive={false}>{Object.keys(mix).map(n=><Cell key={n} fill={REGIME_COLORS[n]}/>)}</Pie><Tooltip formatter={v=>`${(v*100).toFixed(0)}%`} contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/><Legend wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></div>;
export const Reliability=({data,id='reliability-chart'})=><div className="chart-wrap" style={{height:265}} data-testid={id}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:10,right:18,left:-14,bottom:10}}><CartesianGrid stroke="var(--border-soft)"/><XAxis dataKey="bin" type="number" domain={[0,100]} tick={{fill:'var(--text-muted)',fontSize:10}} label={{value:'Forecast probability (%)',position:'insideBottom',offset:-8,fill:'var(--text-muted)',fontSize:10}}/><YAxis yAxisId="prob" domain={[0,100]} tick={{fill:'var(--text-muted)',fontSize:10}}/><YAxis yAxisId="count" orientation="right" hide/><Bar dataKey="count" yAxisId="count" fill="#7995b9" fillOpacity={.12} name="Usage"/><Line dataKey="ideal" yAxisId="prob" stroke="#718096" strokeDasharray="5 5" dot={false} name="Perfect reliability"/><Line dataKey="observed" yAxisId="prob" stroke="#4dd5c4" strokeWidth={2} dot={{r:3}} connectNulls name="Observed frequency" isAnimationActive={false}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/></ComposedChart></ResponsiveContainer></div>;
export const ImprovementChart=({models})=><div className="chart-wrap" style={{height:250}} data-testid="bootstrap-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={models.map(m=>({...m,error:[m.improvement-m.improvement_ci[0],m.improvement_ci[1]-m.improvement]}))} margin={{top:14,right:10,left:-10,bottom:0}}><CartesianGrid stroke="var(--border-soft)" vertical={false}/><XAxis dataKey="id" tick={{fill:'var(--text-muted)',fontSize:10}}/><YAxis tick={{fill:'var(--text-muted)',fontSize:10}}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)'}}/><Bar dataKey="improvement" fill="#4dd5c4" isAnimationActive={false}><ErrorBar dataKey="error" width={6} stroke="#c3ddd9"/></Bar></BarChart></ResponsiveContainer></div>;