import {useEffect,useMemo,useRef,useState} from 'react';
import {MapContainer,GeoJSON,Polyline,Marker,Popup,useMap,useMapEvents} from 'react-leaflet';
import L from 'leaflet';
import {contours as makeContours} from 'd3-contour';
import 'leaflet/dist/leaflet.css';
import {ALERT_COLORS,REGIME_COLORS,RAIN_COLORS,API,pct} from '../lib/api';
import {useSettings} from '../lib/settings';
let geographyPromise;
const geography=()=>geographyPromise||(geographyPromise=Promise.all(['world','districts','india'].map(n=>fetch(`/data/${n}.geojson`).then(r=>{if(!r.ok)throw Error('Boundary file unavailable');return r.json();}))));
const regionBounds={'All India':[[7.5,68],[36,98]],'Western Ghats':[[8,72],[21,78]],'Himalaya':[[27,73],[36,89]],'Indo-Gangetic Plains':[[24,74],[30,89]],'Northeast':[[22,88],[30,98]],'Central India':[[17,73],[25,87]],'Kerala':[[8,74.5],[13,77.5]]};
const rainColor=v=>RAIN_COLORS[[2.5,15.6,64.5,115.6,204.5].filter(t=>v>=t).length];
const labels=[['PAKISTAN',29,67],['CHINA',34,88],['NEPAL',29,84],['BHUTAN',27.7,91],['BANGLADESH',23,90.5],['MYANMAR',21,95.5],['SRI LANKA',7,81.3],['ARABIAN SEA',16,68.6],['BAY OF BENGAL',15,87.7]];
function MapLabels(){const map=useMap();const [visible,setVisible]=useState([]);useEffect(()=>{const update=()=>{const size=map.getSize();setVisible(labels.filter(([,lat,lon])=>{const p=map.latLngToContainerPoint([lat,lon]);return p.x>52&&p.x<size.x-52&&p.y>12&&p.y<size.y-15;}));};update();map.on('moveend resize',update);return()=>map.off('moveend resize',update);},[map]);return visible.map(([text,lat,lon])=><Marker key={text} position={[lat,lon]} interactive={false} icon={L.divIcon({className:'country-label',html:text,iconSize:[100,12],iconAnchor:[50,6]})}/>);}
function MapAccessibility({id}){const map=useMap();useEffect(()=>{const c=map.getContainer();c.setAttribute('data-testid',`${id}-canvas`);c.querySelectorAll('.leaflet-control-zoom a').forEach((a,i)=>a.setAttribute('data-testid',`${id}-zoom-${i===0?'in':'out'}`));},[map,id]);return null;}
function Fit({region,focus}){const map=useMap();useEffect(()=>{const box=focus?[[focus.lat-.7,focus.lon-.8],[focus.lat+.7,focus.lon+.8]]:regionBounds[region];map.fitBounds(box,{padding:[12,12],animate:false});const ro=new ResizeObserver(()=>{map.invalidateSize();map.fitBounds(box,{padding:[12,12],animate:false});});ro.observe(map.getContainer());return()=>ro.disconnect();},[map,region,focus]);return null;}
function Raster({grid,layer='corrected',opacity=.8,clip,clipSide='left',probabilityValues,regime=false}){
 const map=useMap();
 useEffect(()=>{if(!grid)return;const canvas=L.DomUtil.create('canvas','rain-canvas');const pane=map.getPane('overlayPane');pane.appendChild(canvas);canvas.style.pointerEvents='none';canvas.style.opacity=opacity;
 const draw=()=>{const size=map.getSize(),pos=map.containerPointToLayerPoint([0,0]);L.DomUtil.setPosition(canvas,pos);canvas.width=size.x;canvas.height=size.y;const ctx=canvas.getContext('2d');const values=probabilityValues||grid[layer];const names=grid.regime_names;
 if(!values)return;for(let i=0;i<values.length;i++){const v=values[i];if(v==null)continue;const row=Math.floor(i/grid.width),col=i%grid.width;const a=map.latLngToContainerPoint([grid.lats[row]+.125,grid.lons[col]-.125]);const b=map.latLngToContainerPoint([grid.lats[row]-.125,grid.lons[col]+.125]);if(b.x<0||a.x>size.x||b.y<0||a.y>size.y)continue;ctx.globalAlpha=regime?Math.max(.28,grid.confidence[i]):1;ctx.fillStyle=regime?REGIME_COLORS[names[Math.round(v)]]:probabilityValues?['#183c44','#247369','#39a48d','#a4b953','#e2a953','#e97570'][Math.min(5,Math.floor(v*6))]:rainColor(v);ctx.fillRect(a.x,a.y,Math.max(1,b.x-a.x+.4),Math.max(1,b.y-a.y+.4));}if(clip!=null)canvas.style.clipPath=clipSide==='right'?`inset(0 0 0 ${clip}%)`:`inset(0 ${100-clip}% 0 0)`;};draw();map.on('move zoom resize',draw);return()=>{map.off('move zoom resize',draw);canvas.remove();};
 },[map,grid,layer,opacity,clip,clipSide,probabilityValues,regime]);return null;
}
function Contours({grid,thresholds,layer}){const data=useMemo(()=>{if(!grid||!thresholds?.length)return null;const cs=makeContours().size([grid.width,grid.height]).thresholds(thresholds)(grid[layer].map(v=>v??0));return {type:'FeatureCollection',features:cs.map(c=>({type:'Feature',properties:{threshold:c.value},geometry:{type:'MultiPolygon',coordinates:c.coordinates.map(p=>p.map(r=>r.map(([x,y])=>[grid.lons[0]+(x-.5)*.25,grid.lats[0]+(y-.5)*.25])))}}))};},[grid,thresholds,layer]);return data?<GeoJSON key={`${layer}-${thresholds.join()}`} data={data} style={f=>({color:f.properties.threshold===204.5?'#ff72a5':f.properties.threshold===115.6?'#ffc771':'#e2e8f0',weight:1.3,fill:false,dashArray:'3 3'})}/>:null;}
function PointPicker({enabled,dateOverride}){const {date,lead,region,mode}=useSettings();const [point,setPoint]=useState(null);const [state,setState]=useState(null);const serial=useRef(0);useEffect(()=>{serial.current++;setPoint(null);setState(null);},[date,lead,region,mode,dateOverride]);useMapEvents({click:async e=>{if(!enabled)return;const request=++serial.current;setPoint(e.latlng);setState({loading:true});try{const r=await fetch(`${API}/forecast/point?${new URLSearchParams({date:dateOverride||date,lead,region,mode,lat:e.latlng.lat,lon:e.latlng.lng})}`);const d=await r.json();if(request===serial.current)setState(r.ok?d:{error:d.detail});}catch(e){if(request===serial.current)setState({error:'Point product could not be loaded.'});}}});return point?<Popup position={point}><div className="point-readout" data-testid="grid-point-popup">{state?.loading?'Loading grid cell…':state?.error?<p>{state.error}</p>:state&&<><b>{state.lat.toFixed(2)}°N · {state.lon.toFixed(2)}°E</b><div className="popup-subtitle">SYNTHETIC · mm/day</div>{['raw','corrected','observed'].map(n=><div className="popup-row" key={n}><span>{n}</span><b>{state[n]}</b></div>)}<hr/>{Object.entries(state.probabilities).map(([t,p])=><div key={t} className="popup-row"><span>P(≥ {t})</span><b>{pct(p)}</b></div>)}<hr/>{Object.entries(state.mix).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([n,p])=><div key={n} className="popup-row"><span>{n}</span><b>{pct(p)}</b></div>)}</>}</div></Popup>:null;}
export const IndiaMap=({districts,grid,layer='corrected',leftLayer,swipe=50,opacity=.8,probabilityValues,regime=false,thresholds=[],onDistrict,region:regionOverride,focus,dateOverride,small=false,id='india-map'})=>{
 const {region,theme}=useSettings();const renderer=useMemo(()=>L.canvas({padding:0}),[]);const [geo,setGeo]=useState(null);const [error,setError]=useState(null);useEffect(()=>{geography().then(setGeo).catch(e=>setError(e.message));},[]);
 const lookup=useMemo(()=>Object.fromEntries((districts||[]).map(d=>[d.id,d])),[districts]);
 const geoKey=useMemo(()=>`${theme}-${districts?.map(d=>d.id+d.alert).join('')}`,[theme,districts]);
 return <div className={`india-map ${small?'small-map':''}`} data-testid={id}>{error?<div className="error-state">{error}</div>:!geo?<div className="skeleton map-skeleton"/>:<MapContainer center={[22,80]} zoom={4} minZoom={3} maxZoom={10} zoomSnap={.1} zoomDelta={.5} zoomAnimation={false} fadeAnimation={false} markerZoomAnimation={false} renderer={renderer} zoomControl={!small} attributionControl={false} scrollWheelZoom={false} preferCanvas={true}>
 <MapAccessibility id={id}/>
 <Fit region={regionOverride||region} focus={focus}/><GeoJSON key={`world-${theme}`} data={geo[0]} style={{color:theme==='dark'?'#324359':'#ccd7db',weight:.6,fillColor:theme==='dark'?'#172536':'#e0e8e9',fillOpacity:1}}/>
 {[10,20,30].map(lat=><Polyline key={`lat-${lat}`} positions={[[lat,60],[lat,105]]} pathOptions={{color:theme==='dark'?'#55718b':'#718a9d',opacity:.14,weight:.5,dashArray:'2 6'}}/>)}
 {[70,80,90].map(lon=><Polyline key={`lon-${lon}`} positions={[[0,lon],[40,lon]]} pathOptions={{color:theme==='dark'?'#55718b':'#718a9d',opacity:.14,weight:.5,dashArray:'2 6'}}/>)}
 {grid&&<Raster grid={grid} layer={regime?'regime':layer} opacity={opacity} probabilityValues={probabilityValues} regime={regime} clip={leftLayer?swipe:undefined} clipSide="right"/>}
 {grid&&leftLayer&&<Raster grid={grid} layer={leftLayer} opacity={opacity} clip={swipe}/>}
 <GeoJSON key={geoKey} data={geo[1]} style={f=>{const d=lookup[f.properties.id];return {color:theme==='dark'?'#779095':'#5b787e',weight:districts?.length?.6:.3,opacity:.55,fillColor:d?ALERT_COLORS[d.alert]:'#243747',fillOpacity:d?.75:grid?0:.25};}} onEachFeature={(f,l)=>{const d=lookup[f.properties.id];if(d){l.bindTooltip(`<div class="district-tooltip"><b>${d.name}</b><span>${d.state}</span><hr/><div>Areal mean <strong>${d.mean} mm</strong></div><div>Max P(64.5) <strong>${pct(d.p64)}</strong></div><div>Regime <strong>${d.regime}</strong></div><div>Alert <strong>${d.alert}</strong></div><small>SYNTHETIC DATA</small></div>`,{sticky:true,direction:'top'});l.on('click',()=>onDistrict?.(d));l.on('mouseover',()=>l.setStyle({weight:1.4,color:'#b5e5d5',fillOpacity:.95}));l.on('mouseout',()=>l.setStyle({weight:.6,color:theme==='dark'?'#779095':'#5b787e',fillOpacity:.75}));}}}/>
 <GeoJSON key={`outline-${theme}`} data={geo[2]} style={{color:theme==='dark'?'#8aadae':'#617f87',weight:1,fill:false,opacity:.7}}/>
 <Contours grid={grid} thresholds={thresholds} layer={layer}/>
 {!small&&<MapLabels/>}
 <PointPicker enabled={!!grid} dateOverride={dateOverride}/>
 </MapContainer>}<div className="map-attribution" data-testid={`${id}-attribution`}>Natural Earth · Historical district boundaries · Non-authoritative</div></div>;
};
export const RainLegend=()=> <div className="rain-legend" data-testid="rainfall-legend"><span>Rainfall <b>mm/day</b></span><div className="legend-scale">{RAIN_COLORS.map((c,i)=><div key={c}><i style={{background:c}}/><span>{['< 2.5','2.5–15.6','15.6–64.5','64.5–115.6','115.6–204.5','≥ 204.5'][i]}</span></div>)}</div></div>;