import {useState,useEffect} from 'react';
import {NavLink,useLocation,useNavigate} from 'react-router-dom';
import {LayoutDashboard,Workflow,Layers3,CloudRain,Table2,ChartNoAxesCombined,History,Radio,Network,BookOpen,PanelLeftClose,Menu,Sun,Moon,Play,ChevronDown,ArrowRight,X,Activity,ArrowUpRight,Compass} from 'lucide-react';
import {useSettings} from '../lib/settings';
import {useApi} from '../lib/api';
import {Btn,Breadcrumb} from './Primitives';
export const NAV=[['/', 'Command Center',LayoutDashboard],['/regimes','Regime Engine',Workflow],['/forecast','Forecast Viewer',Layers3],['/probabilities','Heavy-Rain Probabilities',CloudRain],['/districts','District Product',Table2],['/verification','Verification Report',ChartNoAxesCombined],['/case-study','Case Study',History],['/alerts','Alerts & API',Radio],['/architecture','Architecture & Ops',Network],['/methodology','Methodology & Data',BookOpen]];
const TOUR=[{path:'/',title:'The monsoon, at a glance',text:'District risk, the prevailing regime, and priority locations share one forecast cycle. Every product here is synthetic.',target:'District alert overview'},{path:'/forecast',title:'See the correction',text:'Drag the map divider to compare displaced, drizzly Raw NWP with the sharper corrected field. Click a land grid cell for exact values.',target:'Swipe comparison'},{path:'/probabilities',title:'From rainfall to probability',text:'Switch between raw and isotonic-calibrated probabilities. Reliability, detection and false alarms are calculated from synthetic fields.',target:'Heavy-rain calibration'},{path:'/verification',title:'Make the evidence inspectable',text:'Explore nine surrogate experiments and computed verification scores. These illustrate the evaluation framework—not measured model skill.',target:'Experiment ladder'},{path:'/districts',title:'Turn forecasts into district products',text:'Inspect district details, adjust provisional alert rules, and export a bulletin. These test products are not official warnings.',target:'District decision support'}];
export const Layout=({children})=>{
 const s=useSettings();const location=useLocation();const navigate=useNavigate();const [collapsed,setCollapsed]=useState(false);const [mobile,setMobile]=useState(false);const [tour,setTour]=useState(-1);const meta=useApi('/metadata');
 const current=NAV.find(n=>n[0]===location.pathname)?.[1]||'Command Center';
 useEffect(()=>{setMobile(false);window.scrollTo(0,0);},[location.pathname]);
 const goTour=i=>{setTour(i);if(i>=0&&i<TOUR.length)navigate(TOUR[i].path);};
 return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}>
 {mobile&&<button aria-label="Close navigation" className="mobile-overlay" data-testid="mobile-nav-overlay" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'mobile-open':''}`}><NavLink to="/" className="brand" data-testid="brand-home"><span className="brand-mark"><CloudRain size={23} strokeWidth={1.7}/></span><span className="brand-word">Monsoon<span>Lens</span><small>REGIME-AWARE INTELLIGENCE</small></span></NavLink>
 <div className="workspace-label">FORECAST WORKSPACE</div><nav>{NAV.map(([path,label,Icon],i)=><div key={path}>{i===7&&<div className="nav-separator"/>}<NavLink data-testid={`nav-${path==='/'?'command':path.slice(1)}`} to={path} end title={label} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon size={18} strokeWidth={1.6}/><span>{label}</span>{path==='/forecast'&&<small>NEW</small>}</NavLink></div>)}</nav>
 <div className="sidebar-bottom"><div className="system-status"><span className="status-dot"/><span>Demo engine ready</span><Activity size={13}/></div><div className="agency-label">SMART INDIA HACKATHON 2026<br/><strong>Ministry of Earth Sciences</strong><span>NCMRWF · PS 26080</span></div><button className="collapse-btn" data-testid="collapse-sidebar" onClick={()=>setCollapsed(!collapsed)} title={collapsed?'Expand sidebar':'Collapse sidebar'}><PanelLeftClose size={17}/><span>Collapse sidebar</span></button></div></aside>
 <div className="workspace"><header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" data-testid="mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="Open navigation"><Menu size={21}/></button><Breadcrumb name={current}/><span className="sih-tag" data-testid="sih-tag">SIH 2026 <i/> PS 26080</span></div><div className="topbar-right"><span className="demo-badge" data-testid="demo-data-badge"><i/>DEMO DATA</span><div className="mode-toggle" role="group" aria-label="Data mode"><button className={s.mode==='demo'?'selected':''} data-testid="mode-demo" onClick={()=>s.setMode('demo')}>Demo</button><button className={s.mode==='live'?'selected':''} data-testid="mode-live" onClick={()=>s.setMode('live')}>Live</button></div><button className="icon-button" data-testid="theme-toggle" onClick={()=>s.setTheme(s.theme==='dark'?'light':'dark')} title="Toggle light and dark theme" aria-label="Toggle theme">{s.theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><Btn id="demo-tour-start" icon={Play} onClick={()=>{s.setMode('demo');goTour(0);}}>Demo tour</Btn><div className="user-avatar" title="Prototype workspace">ML</div></div></header>
 <div className="global-filters">
   <div className="cycle-label"><span className="status-dot"/>FORECAST CYCLE <span className="cycle-hour">00 UTC</span></div>
   <div className="filter-controls">
     <label className="global-control"><span>Initialization</span><input data-testid="global-date" aria-label="Initialization date" type="date" min="2000-01-01" max="2100-12-31" value={s.date} onChange={e=>e.target.value&&s.setDate(e.target.value)}/></label>
     <label className="global-control lead-control"><span>Lead time</span><select data-testid="global-lead" value={s.lead} onChange={e=>s.setLead(+e.target.value)}>{[1,2,3,4,5].map(d=><option value={d} key={d}>{`Day ${d} · +${d*24}h`}</option>)}</select></label>
     <label className="global-control"><span>Region</span><select data-testid="global-region" value={s.region} onChange={e=>s.setRegion(e.target.value)}>{(meta.data?.regions||[{name:'All India'}]).map(r=><option key={r.name}>{r.name}</option>)}</select></label>
   </div>
   <span className="grid-resolution">0.25° GRID <span>·</span> 24 H ACCUMULATION</span>
 </div>
 {s.mode==='live'&&<div className="live-banner" data-testid="live-unavailable-banner"><Radio size={15}/><span><b>Live service not connected.</b> Service URL, authentication and response examples are required. No demo data will be substituted.</span><button data-testid="return-to-demo" onClick={()=>s.setMode('demo')}>Return to demo <ArrowRight size={14}/></button></div>}
 <main className="main-content">{children}</main><footer className="footer"><span><span className="footer-dot"/> Synthetic data for prototype demonstration. Metrics are illustrative, not measured results.</span><span>MONSOONLENS <i> / </i> PROTOTYPE v0.1</span></footer></div>
 {tour>=0&&tour<TOUR.length&&<div className="tour-card" role="dialog" aria-label="Guided demo tour" data-testid="demo-tour"><div className="tour-top"><span><Compass size={15}/> A 60-SECOND FIELD GUIDE</span><button className="icon-button" data-testid="tour-close" aria-label="Close tour" onClick={()=>goTour(-1)}><X size={16}/></button></div><div className="tour-progress">{TOUR.map((t,i)=><i className={i<=tour?'complete':''} key={i}/>)}</div><h2>{TOUR[tour].title}</h2><p>{TOUR[tour].text}</p><div className="tour-bottom"><span>{tour+1} / {TOUR.length} <b> {TOUR[tour].target}</b></span><Btn primary id="tour-next" icon={ArrowRight} onClick={()=>goTour(tour===4?-1:tour+1)}>{tour===4?'Finish':'Next'}</Btn></div></div>}
 </div>;
};