import {useState} from 'react';
import {History,ChevronLeft,ChevronRight,Clock3} from 'lucide-react';
import {useApi,REGIME_COLORS} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,Btn,Notice,MixBars} from '../components/Primitives';
import {IndiaMap,RainLegend} from '../components/IndiaMap';
import {Chart} from '../components/Charts';
export default function CaseStudy(){
 const {lead}=useSettings();const [index,setIndex]=useState(6);const state=useApi('/case-study');const date=`2018-08-${10+index}`;const grid=useApi('/forecast/grid',{date,region:'Kerala'});const names=Object.keys(REGIME_COLORS).filter(n=>n!=='Mixed');
 return <><PageTitle eyebrow="HISTORICAL CONTEXT · SYNTHETIC RECONSTRUCTION" title="Kerala, August 2018" description="An event-inspired case study of displaced rain cores and orographic amplification."><span className="technical-tag"><History size={14}/> 10–19 AUG 2018</span></PageTitle><Notice id="case-study-disclaimer">This is a synthetic reconstruction, not observed flood-event data. The event dates and Kerala region are fixed for this case study; the global lead-day selector remains active.</Notice><Async state={state}>{data=><><div className="case-scrubber"><Btn id="case-previous" icon={ChevronLeft} disabled={index===0} onClick={()=>setIndex(i=>i-1)}/><div className="case-days">{data.timeline.map((d,i)=><button data-testid={`case-day-${i}`} key={d.date} className={i===index?'active':''} onClick={()=>setIndex(i)}><small>AUG</small><b>{i+10}</b><span className="case-day-bar" style={{height:`${5+d.observed/10}px`}}/></button>)}</div><Btn id="case-next" icon={ChevronRight} disabled={index===9} onClick={()=>setIndex(i=>i+1)}/></div><input className="case-range" data-testid="case-date-scrubber" aria-label="Kerala event date" type="range" min="0" max="9" value={index} onChange={e=>setIndex(+e.target.value)}/><div className="case-date-label" data-testid="case-selected-date">{date} <span>· Day {lead} · 08:30–08:30 IST</span></div><Async state={grid}>{g=><div className="case-maps">{[['raw','Raw NWP'],['corrected','MonsoonLens corrected'],['observed','Synthetic observation']].map(([layer,label])=><section key={layer}><SectionHead title={label}/><IndiaMap id={`case-map-${layer}`} grid={g} layer={layer} region="Kerala" dateOverride={date} small/><div className="case-map-stat"><span>Kerala areal mean</span><b>{data.timeline[index][layer].toFixed(1)} <small>mm/day</small></b></div></section>)}</div>}</Async><RainLegend/><div className="case-analysis"><section><SectionHead title="The orographic signal" sub="Synthetic event evolution · regional mean rainfall"/><Chart id="case-rainfall-chart" data={data.timeline.map(d=>({...d,'Raw NWP':d.raw,'Corrected':d.corrected,'Observed':d.observed}))} x="day" keys={['Raw NWP','Corrected','Observed']} height={260}/><p className="body-copy" data-testid="case-narrative">{data.narrative}</p></section><section><SectionHead title="Regime composition" sub={date}/><MixBars id="case-regime" mix={Object.fromEntries(names.map(n=>[n,data.timeline[index][n]]))}/><div className="warning-gained"><Clock3 size={23}/><div><small>ILLUSTRATIVE WARNING GAINED</small><strong data-testid="case-warning-gained">{data.warning_hours==null?'Not resolved':`${data.warning_hours} hours`}</strong></div></div><p className="micro-copy">{data.warning_note}</p></section></div></>}</Async></>;
}