import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowRight,Clock3,Timer,CloudRain,ScanLine,ChevronRight,Download,Info} from 'lucide-react';
import {useApi,pct,ALERT_COLORS,download} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,Metric,MixBars,AlertChip,RegimeChip,Btn,TextLink} from '../components/Primitives';
import {IndiaMap,RainLegend} from '../components/IndiaMap';
import {Sparkline} from '../components/Charts';
import {DistrictDetail} from './Districts';
export default function CommandCenter(){
 const {date,lead,region,alertCutoff}=useSettings();const state=useApi('/overview',{cutoff:alertCutoff});const grid=useApi('/forecast/grid');const [view,setView]=useState('alerts');const [selected,setSelected]=useState(null);const navigate=useNavigate();
 return <><PageTitle title="Command Center" description="A clear view of the monsoon. From atmospheric regimes to district-level risk."><div className="product-time" data-testid="valid-period"><span className="status-dot"/>Day {lead} outlook <i/> {new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</div><Btn id="command-export" icon={Download} onClick={()=>state.data&&download(JSON.stringify(state.data,null,2),`meghdrishti-${date}.json`)} disabled={!state.data}>Export snapshot</Btn></PageTitle>
 <Async state={state}>{data=><>
 <div className="kpi-strip"><div className="metric alert-metric" data-testid="district-alert-metric"><div className="metric-label">Districts under alert <span title="District maximum calibrated exceedance probability meets the configured cutoff." tabIndex={0}><Info size={12}/></span></div><div className="alert-counts">{['Red','Orange','Yellow'].map(a=><div key={a} style={{color:ALERT_COLORS[a]}}><strong data-testid={`count-${a.toLowerCase()}`}>{data.counts[a]}</strong><span><i style={{background:ALERT_COLORS[a]}}/>{a}</span></div>)}</div><div className="metric-sub">of {data.districts.length} historical districts</div></div>
 <Metric id="dominant-regime" label="Dominant regime" value={data.dominant} color="#5595f5" tip="Regionally averaged soft regime weights; synthetic, not a trained classifier." sub={<span className="sub-tag">{pct(data.mix[data.dominant])} regional probability</span>}/>
 <Metric id="heavy-probability" label="Highest heavy-rain probability" value={pct(data.highest_probability)} tip="Highest district maximum probability of rainfall ≥64.5 mm/day." sub="P(rain ≥ 64.5 mm/day)" color="var(--accent-teal)"/>
 <Metric id="last-run" label="Last model run" value="00:00" unit="UTC" tip="Initialization time of this synthetic forecast cycle." sub={`${new Date(data.run_time).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'})} · Synthetic cycle`} icon={Clock3}/>
 <Metric id="latency" label="Product latency" value={data.latency_seconds} unit="sec" tip={data.latency_note} sub={<span className="sub-tag"><span className="status-dot"/>Demo engine ready</span>} icon={Timer}/></div>
 <div className="command-main"><section className="map-section"><SectionHead title="District alert overview" sub={`${region} · Valid ${data.valid_date} · 24-hour accumulated rainfall`}><div className="segmented"><button data-testid="map-alert-layer" className={view==='alerts'?'selected':''} onClick={()=>setView('alerts')}>Alerts</button><button data-testid="map-rain-layer" className={view==='rain'?'selected':''} onClick={()=>setView('rain')}>Rainfall</button></div></SectionHead><div className="command-map-wrap">{view==='alerts'?<IndiaMap districts={data.districts} onDistrict={setSelected}/>:<Async state={grid}>{g=><IndiaMap grid={g}/>}</Async>}<div className="map-corner"><span className="status-dot"/> {view==='alerts'?'DISTRICT ALERT LEVEL':'CORRECTED RAINFALL'}<small>IMD DAY · 08:30–08:30 IST</small></div><div className="map-north">N<span>↑</span></div><div className="map-coordinate">INDIA <span>20.5937° N · 78.9629° E</span></div></div><div className="map-bottom">{view==='alerts'?<div className="alert-legend">{['Green','Yellow','Orange','Red'].map(a=><span key={a}><i style={{background:ALERT_COLORS[a]}}/>{a}<small>{['No warning','Be aware','Be prepared','Take action'][['Green','Yellow','Orange','Red'].indexOf(a)]}</small></span>)}</div>:<RainLegend/>}<span className="provisional-label">Provisional alert mapping <Info size={12}/></span></div></section>
 <aside className="regime-now"><SectionHead title="Regime now"><span className="live-label"><i/>SYNTHETIC</span></SectionHead><div className="regime-headline"><span className="regime-icon"><CloudRain size={24}/></span><div><small>PREVAILING PATTERN</small><h3 data-testid="regime-now-dominant">{data.dominant} monsoon</h3></div></div><MixBars mix={data.mix} id="command-regime" mixed={data.mixed}/><div className="confidence-block"><div><span title="Mean maximum grid-cell regime weight, not an evaluated confidence interval.">Spatial confidence <Info size={11}/></span><b data-testid="regime-confidence">{pct(data.confidence)}</b></div><div className="confidence-track"><i style={{width:`${data.confidence*100}%`}}/></div><small>Mean dominant-regime probability</small></div><TextLink id="explore-regimes" onClick={()=>navigate('/regimes')}>Explore regime engine</TextLink></aside></div>
 <section className="risk-section"><SectionHead title="Districts to watch" sub="Highest-risk locations, ranked by alert severity and extreme-rain probability"><TextLink id="view-all-districts" onClick={()=>navigate('/districts')}>All district products</TextLink></SectionHead><div className="table-wrap"><table className="data-table risk-table" data-testid="risk-district-table"><thead><tr><th>RANK</th><th>DISTRICT / STATE</th><th>ALERT LEVEL</th><th>AREAL MEAN <small>mm/day</small></th><th>MAX P(≥ 64.5)</th><th>PREVAILING REGIME</th><th>5-DAY OUTLOOK</th><th/></tr></thead><tbody>{data.districts.slice(0,10).map((d,i)=><tr key={d.id} data-testid={`risk-row-${d.id}`} onClick={()=>setSelected(d)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setSelected(d)}><td className="rank-cell">{String(i+1).padStart(2,'0')}</td><td><strong>{d.name}</strong><small>{d.state}</small></td><td><AlertChip id={`risk-alert-${d.id}`} level={d.alert}/></td><td className="mono">{d.mean.toFixed(1)}<span className="muted"> mm</span></td><td className="mono probability-cell"><span className="tiny-bar"><i style={{width:`${d.p64*100}%`}}/></span>{pct(d.p64)}</td><td><RegimeChip id={`risk-regime-${d.id}`} name={d.regime} mixed={d.mixed}/></td><td><Sparkline id={`outlook-${d.id}`} data={d.outlook}/></td><td><ChevronRight size={15}/></td></tr>)}</tbody></table></div></section>
 </>}</Async><DistrictDetail district={selected} onClose={()=>setSelected(null)}/></>;
}