import {useMemo,useState,useEffect,useRef} from 'react';
import {Search,Download,Settings2,ArrowUpDown,MapPin,SlidersHorizontal} from 'lucide-react';
import {useApi,API,pct,download,REGIME_COLORS} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,AlertChip,RegimeChip,Btn,Select,Drawer,MixBars,Empty,Notice} from '../components/Primitives';
import {IndiaMap} from '../components/IndiaMap';
import {Chart,Donut} from '../components/Charts';
import {toast} from 'sonner';
export const DistrictDetail=({district:d,onClose})=>{
 const {date,lead,region,mode,alertCutoff,alertThresholds}=useSettings();const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{closeRef.current();},[date,lead,region,mode,alertCutoff,alertThresholds]);
 return <Drawer open={!!d} onClose={onClose} title={d?.name||'District detail'} description={`${d?.state||''} · Synthetic district product`} id="district-detail">{d&&<>
   <div className="drawer-alert"><AlertChip id="detail-alert" level={d.alert}/><RegimeChip id="detail-regime" name={d.regime} mixed={d.mixed}/></div>
   <IndiaMap districts={[d]} focus={d} small id="district-mini-map"/>
   <div className="detail-kpis">{[['Areal mean',`${d.mean} mm`],['Peak grid',`${d.peak} mm`],['Max P(64.5)',pct(d.p64)]].map(([l,v])=><div key={l} data-testid={`detail-metric-${l.replaceAll(' ','-')}`}><small>{l}</small><strong>{v}</strong></div>)}</div>
   <SectionHead title="Raw vs corrected" sub="District areal mean · mm/day"/>
   <Chart id="district-comparison" type="bar" x="name" keys={['Raw NWP','Corrected','Observed']} data={[{name:d.name,'Raw NWP':d.raw,Corrected:d.mean,Observed:d.observed}]} height={170}/>
   <SectionHead title="5-day heavy-rain probability" sub="District maximum P(≥ 64.5 mm/day)"/>
   <Chart id="district-five-day" data={d.outlook.map(x=>({day:`Day ${x.day}`,'P(≥64.5)':x.probability}))} keys={['P(≥64.5)']} x="day" domain={[0,100]} height={175} percent/>
   <SectionHead title="Prevailing regime mixture"/><Donut mix={d.mix}/>
   <Notice id="district-suggested-action">{d.action}</Notice><p className="micro-copy">Provisional suggested action. To be confirmed with NCMRWF/IMD. Not an official warning.</p>
 </>}</Drawer>;
};
export default function Districts(){
 const s=useSettings();const thresholds=s.alertThresholds;const setThresholds=s.setAlertThresholds;const [draft,setDraft]=useState(thresholds);const [draftCut,setDraftCut]=useState(s.alertCutoff);const state=useApi('/forecast/districts',{cutoff:s.alertCutoff,...thresholds});const [query,setQuery]=useState('');const [stateFilter,setStateFilter]=useState('All states');const [alert,setAlert]=useState('All alerts');const [regime,setRegime]=useState('All regimes');const [sort,setSort]=useState({key:'peak',dir:-1});const [selected,setSelected]=useState(null);const [settings,setSettings]=useState(false);const [page,setPage]=useState(0);const [exporting,setExporting]=useState(false);
 const rows=useMemo(()=>{let ds=state.data?.districts||[];return ds.filter(d=>`${d.name} ${d.state}`.toLowerCase().includes(query.toLowerCase())&&(stateFilter==='All states'||d.state===stateFilter)&&(alert==='All alerts'||d.alert===alert)&&(regime==='All regimes'||d.regime===regime)).sort((a,b)=>typeof a[sort.key]==='string'?a[sort.key].localeCompare(b[sort.key])*sort.dir:(a[sort.key]-b[sort.key])*sort.dir);},[state.data,query,stateFilter,alert,regime,sort]);
 useEffect(()=>setPage(0),[query,stateFilter,alert,regime,state.data]);
 const changeSort=key=>setSort({key,dir:sort.key===key?-sort.dir:-1});
 const exportCSV=()=>{const keys=['name','state','mean','peak','p64','p115','p204','regime','alert','action'];const quote=v=>`"${String(v).replaceAll('"','""')}"`;download([['SYNTHETIC DATA — illustrative, not official alerts'],keys,...rows.map(d=>keys.map(k=>d[k]))].map(r=>r.map(quote).join(',')).join('\n'),`monsoonlens-districts-${s.date}.csv`,'text/csv');toast.success('District CSV exported');};
 const exportGeo=async()=>{setExporting(true);try{const r=await fetch(`${API}/forecast/districts?${new URLSearchParams({date:s.date,lead:s.lead,region:s.region,mode:s.mode,cutoff:s.alertCutoff,...thresholds,format:'geojson'})}`);if(!r.ok)throw Error('Export unavailable');const data=await r.json();const ids=new Set(rows.map(d=>d.id));data.features=data.features.filter(f=>ids.has(f.properties.id));download(JSON.stringify(data),`monsoonlens-districts-${s.date}.geojson`,'application/geo+json');toast.success('Filtered GeoJSON exported');}catch(e){toast.error(e.message);}finally{setExporting(false);}};
 const cols=[['name','District'],['state','State'],['mean','Areal mean'],['peak','Peak grid'],['p64','P(≥64.5)'],['p115','P(≥115.6)'],['p204','P(≥204.5)'],['regime','Regime'],['alert','Alert']];
 return <><PageTitle title="District Product" description="A district-level view of rainfall risk, with actionable, provisional alert products."><Btn id="alert-settings" icon={Settings2} onClick={()=>{setDraft(thresholds);setDraftCut(s.alertCutoff);setSettings(true);}}>Alert settings</Btn><Btn id="district-export-csv" icon={Download} onClick={exportCSV} disabled={!state.data}>CSV</Btn><Btn id="district-export-geojson" icon={Download} onClick={exportGeo} disabled={!state.data||exporting}>{exporting?'Exporting…':'GeoJSON'}</Btn></PageTitle>
 <div className="filter-bar"><label className="search-box"><Search size={16}/><input data-testid="district-search" placeholder="Search district or state…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select id="district-state-filter" value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option>All states</option>{[...new Set((state.data?.districts||[]).map(d=>d.state))].sort().map(n=><option key={n}>{n}</option>)}</Select><Select id="district-alert-filter" value={alert} onChange={e=>setAlert(e.target.value)}>{['All alerts','Red','Orange','Yellow','Green'].map(n=><option key={n}>{n}</option>)}</Select><Select id="district-regime-filter" value={regime} onChange={e=>setRegime(e.target.value)}>{['All regimes',...Object.keys(REGIME_COLORS).filter(n=>n!=='Mixed')].map(n=><option key={n}>{n}</option>)}</Select><span className="result-count" data-testid="district-result-count">{rows.length} districts</span></div>
 <Async state={state}>{data=><><div className="table-wrap"><table className="data-table district-table" data-testid="district-product-table"><thead><tr>{cols.map(([key,label])=><th key={key}><button data-testid={`sort-${key}`} onClick={()=>changeSort(key)}>{label}<ArrowUpDown size={11}/></button></th>)}<th>Suggested action</th></tr></thead><tbody>{rows.slice(page*20,(page+1)*20).map(d=><tr key={d.id} data-testid={`district-row-${d.id}`} onClick={()=>setSelected(d)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setSelected(d)}><td data-label="District"><strong>{d.name}</strong></td><td data-label="State">{d.state}</td><td data-label="Areal mean" className="mono">{d.mean} <small>mm</small></td><td data-label="Peak" className="mono">{d.peak} <small>mm</small></td><td data-label="P(64.5)" className="mono">{pct(d.p64)}</td><td data-label="P(115.6)" className="mono">{pct(d.p115)}</td><td data-label="P(204.5)" className="mono">{pct(d.p204)}</td><td data-label="Regime"><RegimeChip id={`district-regime-${d.id}`} name={d.regime}/></td><td data-label="Alert"><AlertChip id={`district-alert-${d.id}`} level={d.alert}/></td><td data-label="Action" className="action-cell">{d.action}</td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div><div className="pagination"><span data-testid="district-pagination">{rows.length?`${page*20+1}–${Math.min((page+1)*20,rows.length)} of ${rows.length}`:'0 results'}</span><div><Btn id="district-prev" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</Btn><Btn id="district-next" disabled={(page+1)*20>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</Btn></div></div><Notice>Alert rules are provisional, to be confirmed with NCMRWF/IMD. Historical boundary coverage: 594 districts.</Notice></>}</Async>
 <DistrictDetail district={selected} onClose={()=>setSelected(null)}/><Drawer open={settings} onClose={()=>setSettings(false)} title="Alert mapping" description="Provisional thresholds · to be confirmed with NCMRWF/IMD" id="alert-settings-drawer"><p className="body-copy">Assign the highest alert whose district maximum exceedance probability meets the probability cutoff.</p>{Object.entries(draft).map(([name,v])=><label className="settings-field" key={name}><span>{name} rainfall threshold <small>mm/day</small></span><input data-testid={`alert-threshold-${name}`} type="number" min="1" max="500" step=".1" value={v} onChange={e=>setDraft({...draft,[name]:+e.target.value})}/></label>)}<label className="settings-field"><span>Probability cutoff <b>{pct(draftCut)}</b></span><input data-testid="alert-cutoff" type="range" min=".1" max=".95" step=".05" value={draftCut} onChange={e=>setDraftCut(+e.target.value)}/></label><Btn primary id="save-alert-settings" onClick={()=>{if(!(draft.yellow>0&&draft.yellow<draft.orange&&draft.orange<draft.red&&draft.red<=500)){toast.error('Thresholds must increase: Yellow < Orange < Red (maximum 500 mm).');return;}setThresholds(draft);s.setAlertCutoff(draftCut);setSettings(false);toast.success('Provisional alert mapping updated');}}>Apply alert mapping</Btn><Notice>Settings apply to this workspace session. These thresholds do not establish official warning criteria.</Notice></Drawer></>;
}