import {useState} from 'react';
import {Layers3,MoveHorizontal,Info,MapPin} from 'lucide-react';
import {useApi} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,Select,Notice} from '../components/Primitives';
import {IndiaMap,RainLegend} from '../components/IndiaMap';
const LAYERS={raw:'Raw NWP',corrected:'MonsoonLens corrected',observed:'IMD observation · synthetic'};
export default function Forecast(){
 const state=useApi('/forecast/grid');const {lead,setLead}=useSettings();const [left,setLeft]=useState('raw');const [right,setRight]=useState('corrected');const [swipe,setSwipe]=useState(50);const [opacity,setOpacity]=useState(.85);const [thresholds,setThresholds]=useState([]);
 return <><PageTitle title="Forecast Viewer" description="One atmosphere. Two perspectives. Inspect the correction at every grid cell."><span className="technical-tag"><Layers3 size={14}/> 0.25° SPATIAL RESOLUTION</span></PageTitle><div className="forecast-toolbar"><div className="layer-selectors"><Select id="left-map-layer" label="LEFT LAYER" value={left} onChange={e=>setLeft(e.target.value)}>{Object.entries(LAYERS).map(([v,n])=><option value={v} key={v}>{n}</option>)}</Select><MoveHorizontal size={18}/><Select id="right-map-layer" label="RIGHT LAYER" value={right} onChange={e=>setRight(e.target.value)}>{Object.entries(LAYERS).map(([v,n])=><option value={v} key={v}>{n}</option>)}</Select></div><div className="contour-controls"><span>CONTOURS</span>{[64.5,115.6,204.5].map(t=><label key={t}><input data-testid={`contour-${t}`} type="checkbox" checked={thresholds.includes(t)} onChange={e=>setThresholds(e.target.checked?[...thresholds,t]:thresholds.filter(n=>n!==t))}/>{t}</label>)}</div><label className="opacity-control">Opacity <input data-testid="map-opacity" type="range" min=".2" max="1" step=".05" value={opacity} onChange={e=>setOpacity(+e.target.value)}/><span>{Math.round(opacity*100)}%</span></label></div>
 <Async state={state}>{data=><><div className="forecast-map" data-testid="swipe-comparison"><IndiaMap grid={data} layer={right} leftLayer={left} swipe={swipe} opacity={opacity} thresholds={thresholds}/><div className="map-layer-tag left" data-testid="left-layer-label"><span/> {LAYERS[left]}</div><div className="map-layer-tag right" data-testid="right-layer-label"><span/> {LAYERS[right]}</div><div className="swipe-divider" style={{left:`${swipe}%`}}><div className="swipe-handle"><MoveHorizontal size={21}/></div></div><input data-testid="forecast-swipe-slider" className="swipe-range" aria-label="Swipe map comparison divider" type="range" min="5" max="95" value={swipe} onChange={e=>setSwipe(+e.target.value)}/><div className="map-metrics" data-testid="visible-region-metrics"><span>{LAYERS[right]}</span>{['bias','rmse','fss'].map(k=><div key={k} title={{bias:'Mean error versus synthetic truth, mm/day.',rmse:'Root mean square error versus synthetic truth, mm/day.',fss:'Fractions skill score at 50 km for ≥64.5 mm/day.'}[k]}><small>{k.toUpperCase()}</small><b>{data.metrics[right][k].toFixed(2)}</b></div>)}</div></div><div className="forecast-bottom"><RainLegend/><div className="accumulation-label"><ClockIcon/>IMD rainfall day <strong>08:30 to 08:30 IST</strong></div></div><div className="lead-timeline"><span>FORECAST LEAD</span><input data-testid="forecast-lead-slider" type="range" min="1" max="5" step="1" value={lead} onChange={e=>setLead(+e.target.value)}/><div className="lead-buttons">{[1,2,3,4,5].map(d=><button data-testid={`forecast-day-${d}`} key={d} className={d===lead?'selected':''} onClick={()=>setLead(d)}>Day {d}<small>+{d*24}h</small></button>)}</div></div><Notice>“IMD observation” is a synthetic reference field, not an IMD data feed. Corrected fields are controlled perturbations of synthetic truth, not trained-model predictions.</Notice></>}</Async></>;
}
const ClockIcon=()=> <Info size={14}/>;