import {useState} from 'react';
import {SlidersHorizontal,Info} from 'lucide-react';
import {useApi,pct} from '../lib/api';
import {Async,PageTitle,SectionHead,Metric,Notice} from '../components/Primitives';
import {IndiaMap} from '../components/IndiaMap';
import {Reliability} from '../components/Charts';
export default function Probabilities(){
 const [threshold,setThreshold]=useState(64.5);const [calibrated,setCalibrated]=useState(true);const [cutoff,setCutoff]=useState(.5);const grid=useApi('/forecast/grid');const state=useApi('/probabilities',{threshold,calibrated,cutoff});
 return <><PageTitle title="Heavy-Rain Probabilities" description="Beyond a single forecast: quantify exceedance risk and inspect probability reliability."><span className="technical-tag">ISOTONIC CALIBRATION</span></PageTitle><div className="probability-toolbar"><div className="threshold-tabs">{[64.5,115.6,204.5].map((t,i)=><button data-testid={`probability-threshold-${t}`} className={threshold===t?'active':''} onClick={()=>setThreshold(t)} key={t}><span>{['Heavy','Very heavy','Extremely heavy'][i]}</span><b>P(≥ {t} <small>mm/day</small>)</b></button>)}</div><div className="segmented"><button data-testid="prob-uncalibrated" className={!calibrated?'selected':''} onClick={()=>setCalibrated(false)}>Uncalibrated</button><button data-testid="prob-calibrated" className={calibrated?'selected':''} onClick={()=>setCalibrated(true)}>Calibrated</button></div></div>
 <Async state={state}>{data=><><div className="probability-layout"><section className="probability-map-section"><SectionHead title="Exceedance probability" sub={`P(rain ≥ ${threshold} mm/day) · ${calibrated?'Isotonic calibrated':'Uncalibrated'}`}/><Async state={grid}>{g=><IndiaMap grid={g} probabilityValues={data.map} id="probability-map"/>}</Async><div className="prob-legend"><span>0%</span>{['#183c44','#247369','#39a48d','#a4b953','#e2a953','#e97570'].map(c=><i key={c} style={{background:c}}/>)}<span>100%</span></div></section><section className="reliability-section"><SectionHead title="Reliability diagram" sub="Observed frequency (%) vs forecast probability (%)"><span title="A perfectly calibrated forecast lies on the diagonal; faint bars show bin usage."><Info size={14}/></span></SectionHead><Reliability data={data.reliability}/><div className="reliability-key"><i/> {calibrated?'Calibrated':'Uncalibrated'} <span>— —</span> Perfect reliability</div><div className="probability-scores"><Metric id="brier-skill" label="Brier Skill Score" value={data.bss.toFixed(3)} tip="Improvement in probability mean-squared error relative to event climatology."/><Metric id="roc-auc" label="ROC AUC" value={data.auc?.toFixed(3)||'N/A'} tip="Discrimination across all probability cutoffs; 1 is perfect, 0.5 is random."/></div></section></div>
 <div className="probability-decision"><div><SectionHead title="Decision threshold" sub="Detection and false alarms at the selected probability cutoff"/><div className="cutoff-slider"><SlidersHorizontal size={18}/><input data-testid="probability-decision-cutoff" type="range" min=".05" max=".95" step=".05" value={cutoff} onChange={e=>setCutoff(+e.target.value)}/><b data-testid="decision-cutoff-value">{pct(cutoff)}</b></div></div><Metric id="probability-pod" label="Probability of detection" value={pct(data.pod)} tip="Observed threshold exceedances correctly forecast at the chosen cutoff."/><Metric id="probability-far" label="False alarm ratio" value={pct(data.far)} color="#eab350" tip="Fraction of predicted threshold exceedances that did not occur."/><div className="sample-count"><b>{data.event_count.toLocaleString()}</b><span>synthetic events<br/>across {data.sample_count.toLocaleString()} land cells</span></div></div><Notice>{data.calibration_note} No operational probability skill is claimed.</Notice></>}</Async></>;
}