import {useMemo} from 'react';
import {Workflow,Info} from 'lucide-react';
import {useApi,REGIME_COLORS,pct} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,RegimeChip,Notice} from '../components/Primitives';
import {IndiaMap} from '../components/IndiaMap';
import {Chart,Reliability} from '../components/Charts';
export default function Regimes(){
 const state=useApi('/regime');const grid=useApi('/forecast/grid');const {date,setDate}=useSettings();const names=Object.keys(REGIME_COLORS).filter(n=>n!=='Mixed');
 return <><PageTitle title="Regime Engine" description="The same rainfall, different physical drivers. Soft regime routing preserves the mixture."><span className="technical-tag"><Workflow size={14}/> PHYSICS-SUPERVISED ROUTING</span></PageTitle><Async state={state}>{data=><>
 <div className="regime-layout"><section className="regime-region-panel"><SectionHead title="Regional regime mixtures" sub="Normalized probabilities · Mixed when ≥2 regimes exceed 30%"/><div className="region-stacks">{data.regions.map(r=><div className="region-stack" key={r.region} data-testid={`regional-mixture-${r.region.replaceAll(' ','-')}`}><div><b>{r.region}</b>{r.mixed&&<span className="mixed-tag">Mixed</span>}</div><div className="stack-bar">{names.map(n=><span key={n} title={`${n}: ${pct(r[n])}`} style={{width:`${r[n]*100}%`,background:REGIME_COLORS[n]}}>{r[n]>.16?`${Math.round(r[n]*100)}%`:''}</span>)}</div></div>)}</div><div className="regime-legend">{names.map(n=><RegimeChip key={n} id={`regime-legend-${n}`} name={n}/>)}</div></section><section className="regime-map-panel"><SectionHead title="Dominant regime field" sub="Opacity encodes grid-level confidence"/><Async state={grid}>{g=><IndiaMap grid={g} regime id="regime-map"/>}</Async></section></div>
 <section className="chart-section season-chart"><SectionHead title="Monsoon season timeline" sub={`JJAS ${date.slice(0,4)} · regional probability mixture`}/><Chart id="regime-season-chart" data={data.timeline} keys={names} x="label" type="area" height={240} domain={[0,1]}/><div className="season-scrubber"><span>01 JUN</span><input data-testid="regime-date-scrubber" type="range" min="0" max={data.timeline.length-1} value={Math.max(0,data.timeline.findIndex(d=>d.date>=date))} onChange={e=>setDate(data.timeline[+e.target.value].date)}/><span>29 SEP</span><b data-testid="regime-selected-date">{date}</b></div></section>
 <section className="rules-section"><SectionHead title="Objective regime definitions" sub="Proposed atmospheric labels and their physical predictors"/><div className="table-wrap"><table className="data-table rules-table" data-testid="regime-objective-rules"><thead><tr><th>REGIME</th><th>OBJECTIVE LABEL RULE</th><th>KEY PREDICTORS</th></tr></thead><tbody>{data.rules.map(r=><tr key={r.regime}><td><RegimeChip id={`rule-${r.regime.replaceAll(' ','-')}`} name={r.regime}/></td><td>{r.rule}</td><td>{r.predictors}</td></tr>)}</tbody></table></div></section>
 <SectionHead title="Classifier quality" sub="Illustrative classification diagnostics — synthetic samples, not a trained classifier"/><div className="quality-grid"><section><h3 className="chart-title">Confusion matrix</h3><div className="confusion-grid" data-testid="confusion-matrix"><div className="matrix-empty"/>{names.map(n=><span className="matrix-label" key={n} title={n}>{n==='Western Disturbance'?'WD':n.slice(0,4)}</span>)}{data.quality.matrix.map((row,i)=><div className="matrix-row" key={i}><span className="matrix-label" title={names[i]}>{names[i]==='Western Disturbance'?'WD':names[i].slice(0,4)}</span>{row.map((v,j)=><span data-testid={`confusion-${i}-${j}`} key={j} title={`True ${names[i]}, predicted ${names[j]}: ${v}`} style={{background:`rgba(66,190,169,${.07+v/Math.max(...data.quality.matrix.flat())*.72})`}}>{v}</span>)}</div>)}</div><p className="micro-copy">Rows: true label · Columns: predicted label</p></section><section><h3 className="chart-title">Per-regime scores</h3><table className="data-table quality-table" data-testid="regime-score-table"><thead><tr><th>REGIME</th><th title="Fraction of predicted labels that are correct.">P</th><th title="Fraction of true labels detected.">R</th><th title="Harmonic mean of precision and recall.">F1</th></tr></thead><tbody>{data.quality.scores.map(r=><tr key={r.regime}><td>{r.regime}</td>{['precision','recall','f1'].map(k=><td className="mono" key={k}>{r[k].toFixed(2)}</td>)}</tr>)}</tbody></table></section><section><h3 className="chart-title">Regime probability calibration</h3><Reliability id="regime-calibration-chart" data={data.quality.calibration.map(d=>({...d,bin:d.forecast,ideal:d.forecast,count:0}))}/></section></div><Notice>{data.quality.note} Label definitions require real atmospheric predictors before scientific validation.</Notice>
 </>}</Async></>;
}