import {useState} from 'react';
import {Download,FlaskConical,Info} from 'lucide-react';
import {useApi,REGIME_COLORS} from '../lib/api';
import {useSettings} from '../lib/settings';
import {Async,PageTitle,SectionHead,Btn,Select,Notice,Empty} from '../components/Primitives';
import {Chart,ImprovementChart} from '../components/Charts';
const KEYS=['bias','mae','rmse','pod','far','csi','ets','hss','fss','bss'];
const Performance=({models})=>{const W=400,H=255,x=v=>45+v*330,y=v=>220-v*190;return <div className="performance-chart" data-testid="performance-diagram"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Performance diagram: probability of detection versus success ratio"><rect x="45" y="30" width="330" height="190" fill="none" stroke="var(--border)"/>{[.2,.4,.6,.8,1].map(v=><g key={v}><path d={`M${x(v)},30V220 M45,${y(v)}H375`} stroke="var(--border-soft)" strokeDasharray="3 3"/><text x={x(v)} y="235" textAnchor="middle">{v}</text><text x="32" y={y(v)+3} textAnchor="end">{v}</text></g>)}{[.1,.3,.5,.7,.9].map(c=>{const points=Array.from({length:101},(_,i)=>i/100).map(sr=>({sr,p:1/(1/c-1/sr+1)})).filter(p=>p.sr>=c&&p.p>=0&&p.p<=1);return <g key={c}><path d={points.map((p,i)=>`${i?'L':'M'}${x(p.sr)},${y(p.p)}`).join(' ')} fill="none" stroke="#6f8193" strokeDasharray="4 4" opacity=".6"/><text x={x(1)-31} y={y(c)-4}>CSI {c}</text></g>})}{models.map((m,i)=><g key={m.id}><circle cx={x(1-m.far)} cy={y(m.pod)} r={i===8?5:3.5} fill={i===8?'#4dd5c4':'#829ebd'}><title>{m.id}: POD {m.pod}, success ratio {(1-m.far).toFixed(3)}</title></circle><text x={x(1-m.far)-6} y={y(m.pod)-6}>{m.id}</text></g>)}<text x="210" y="253" textAnchor="middle">Success ratio (1 − FAR)</text><text x="14" y="125" transform="rotate(-90 14 125)" textAnchor="middle">Probability of detection</text></svg></div>};
export default function Verification(){
 const [threshold,setThreshold]=useState(64.5);const [regime,setRegime]=useState('All regimes');const [period,setPeriod]=useState('2018');const state=useApi('/verification',{threshold,regime,period});const {date,lead,region}=useSettings();
 const printReport=()=>{document.title=`MeghDrishti — Synthetic Verification — ${period}`;window.print();};
 return <><PageTitle title="Verification Report" description="An inspectable evaluation framework. Computed metrics, transparent assumptions."><Btn id="download-verification-report" icon={Download} onClick={printReport} disabled={!state.data||state.data.empty}>Download verification report</Btn></PageTitle>
 <div className="filter-bar">
   <Select id="verification-regime" label="REGIME" value={regime} onChange={e=>setRegime(e.target.value)}>{['All regimes',...Object.keys(REGIME_COLORS).filter(n=>n!=='Mixed')].map(n=><option key={n}>{n}</option>)}</Select>
   <Select id="verification-threshold" label="RAINFALL THRESHOLD" value={threshold} onChange={e=>setThreshold(+e.target.value)}>{[2.5,64.5,115.6,204.5].map(t=><option value={t} key={t}>{`≥ ${t} mm/day`}</option>)}</Select>
   <Select id="verification-period" label="TEST YEAR" value={period} onChange={e=>setPeriod(e.target.value)}>{['2017','2018','2019'].map(y=><option key={y}>{y}</option>)}</Select>
   <span className="filter-summary" data-testid="verification-context">{region} <i>·</i> Day {lead} <i>·</i> 95% bootstrap CI</span>
 </div>
 <Notice id="verification-honesty">Illustrative surrogate experiments, not trained models. Metrics are computed from synthetic fields and must not be presented as operational verification results.</Notice>
 <Async state={state}>{data=>data.empty?<Empty text={data.message}/>:<><div className="print-heading"><h1>MeghDrishti · Synthetic verification summary</h1><p>{region} · Day {lead} · {period} · ≥{threshold} mm/day · {regime}</p><p>SYNTHETIC DATA. Metrics are illustrative, not measured results.</p></div><section className="experiment-section"><SectionHead title="Experiment ladder" sub={`${data.samples.toLocaleString()} grid samples · ${data.dates.length} synthetic dates · 120 day-block bootstrap resamples`}><span className="technical-tag"><FlaskConical size={13}/> M-0 → M-8</span></SectionHead><div className="table-wrap"><table className="data-table experiment-table" data-testid="experiment-ladder"><thead><tr><th>EXPERIMENT / SURROGATE</th>{KEYS.map(k=><th key={k} title={data.metric_tips[k]}>{k.toUpperCase()} <small>{['bias','mae','rmse','far'].includes(k)?'↓':'↑'}</small></th>)}<th>RMSE VS RAW</th></tr></thead><tbody>{data.models.map(m=><tr key={m.id} className={m.id==='M-8'?'ensemble-row':''} data-testid={`experiment-${m.id}`}><td><span className="model-id">{m.id}</span><strong>{m.name}</strong></td>{KEYS.map(k=>{const lower=['bias','mae','rmse','far'].includes(k);const vals=data.models.map(row=>k==='bias'?Math.abs(row[k]):row[k]);const best=lower?Math.min(...vals):Math.max(...vals);const isBest=(k==='bias'?Math.abs(m[k]):m[k])===best;return <td key={k} data-label={k.toUpperCase()} className={`mono ${isBest?'best-metric':''}`} title={`${data.metric_tips[k]} 95% CI: ${m.ci[k][0]} to ${m.ci[k][1]}`}><b>{m[k].toFixed(['bias','mae','rmse'].includes(k)?1:2)}</b><small>±{((m.ci[k][1]-m.ci[k][0])/2).toFixed(['bias','mae','rmse'].includes(k)?1:2)}</small></td>})}<td data-label="RMSE vs raw"><span className={`improvement ${m.improvement<0?'negative':''}`} data-testid={`improvement-${m.id}`}>{m.id==='M-0'?'Baseline':`${m.improvement>=0?'+':''}${m.improvement}%`}</span></td></tr>)}</tbody></table></div><p className="micro-copy">Best values highlighted. Bias uses minimum absolute error. ± is half the bootstrap interval width; hover for exact endpoints.</p></section>
 <div className="verification-charts"><section><SectionHead title="Fractions skill by neighbourhood" sub="FSS · threshold event fraction determines the useful-skill line"/><Chart id="verification-fss" data={data.fss} x="scale" keys={['Raw NWP','Corrected','Useful skill']} domain={[0,1]}/><p className="micro-copy">Neighbourhood scale (km) · Useful skill = 0.5 + f/2</p></section><section><SectionHead title="Performance diagram" sub="Upper-right is better · dashed curves indicate CSI"/><Performance models={data.models}/></section><section><SectionHead title="Categorical skill by threshold" sub="Equitable threat and critical success scores"/><Chart id="verification-threshold-chart" type="bar" data={data.thresholds} x="threshold" keys={['Raw ETS','Corrected ETS','Raw CSI','Corrected CSI']} domain={[0,1]}/></section><section><SectionHead title="Skill gain by regime × lead" sub="RMSE reduction versus raw (%) · selected-date synthetic field"/><div className="skill-heatmap" data-testid="skill-gain-heatmap"><div/>{[1,2,3,4,5].map(l=><span key={l}>Day {l}</span>)}{Object.keys(REGIME_COLORS).filter(n=>n!=='Mixed').map(n=><div className="heatmap-row" key={n}><span>{n}</span>{[1,2,3,4,5].map(l=>{const v=data.heatmap.find(v=>v.regime===n&&v.lead===l)?.gain;return <span key={l} title={`${n}, Day ${l}: ${v??'no samples'}`} style={{background:v==null?'var(--surface)':`rgba(64,190,166,${Math.max(.06,v/130)})`}}>{v==null?'—':`${v.toFixed(0)}%`}</span>})}</div>)}</div></section><section><SectionHead title="The drizzle-bias signature" sub="Frequency of grid cells in each rainfall category (%)"/><Chart id="verification-frequency-chart" type="bar" data={data.frequency} x="category" keys={['Raw NWP','Corrected','Observed']}/></section><section><SectionHead title="RMSE improvement with uncertainty" sub="Improvement vs raw (%) · bootstrap 95% confidence intervals"/><ImprovementChart models={data.models}/></section></div><Notice id="verification-method-note">{data.note}</Notice></>}</Async></>;
}